### PR TITLE
Code cleanup/tv

### LINKED ISSUE #8185: Refactor tv.py
I've selected [**tv.py**](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L1-L0) for refactoring, which is a module that has **13** instance(s) of code in comments ([1](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L241-L241), [2](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L562-L562), [3](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L712-L712), [4](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L720-L720), [5](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L1117-L1117), [6](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L1538-L1538), [7](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L1560-L1560), [8](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2001-L2001), [9](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2027-L2027), [10](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2136-L2136), [11](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2145-L2145), [12](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2299-L2299), [13](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2406-L2406)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Clean Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Apply The Boy Scout Rule and fix "code smells" in the codebase.
- **Why**❓ 
Clean code is maintainable code.
- **How** 🔧 
Remove useless comments, commented code blocks, and dead code. Refactor poorly handled exceptions, magic constants, and poorly named units or variables.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

### PR DESCRIPTION
**Pull request by miigotu**
Fixes #8185 

Proposed changes in this pull request:
- clean up code in comments 
- clean up typos

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

File: contrib/debian-ubuntu-install.sh [hunk 1]
```diff
@@ -30,7 +32,7 @@ internal_ip=$(ip r g 8.8.8.8 | awk 'NR==1{print $7};')
 apt-get -qq install whiptail -y
 
 function check_packages {
-  packages=$(dpkg -l unrar git-core openssl libssl-dev python3.8 2>&1 | grep "no packages" | awk '{ print $6 }' | tr '\n' ' ')
+  packages=$(dpkg -l unrar openssl libssl-dev python3.9 2>&1 | grep "no packages" | awk '{ print $6 }' | tr '\n' ' ')
```
Comment (ghost) [inline contrib/debian-ubuntu-install.sh]: python3.9 is not available for ubuntu 22.04 LTS, unless you use ppa's
Default is 3.10

`dpkg -l unrar openssl libssl-dev python3 2>&1 | grep "dpkg-query" | awk '{ print $NF }' | tr '\n' ' '` works better for non english speaking systems, or it will fail to detect and install packages
